Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,9 +30,16 @@ jobs:
               run: |
                   cd quoterepo/serverSide
                   node testAllQuotes.js
+
+                  TEST=$(node testAllQuotes.js)
+                  echo "${TEST}"
+
+                  SUB='FAIL'
+                  if [[ "$TEST" == *"$SUB"* ]]; then
+                    echo 'Unit tests fail'
+                    exit 1 
+                    fi
                   cd ..
                   tar -cvf deployment.tar data serverSide
                   gzip deployment.tar
                   ls
-
-            
